### ISSUE TITLE
Acrylic doesn't update automatically

### ISSUE THREAD

**Issue by ilopX** [alexmercerind/flutter_acrylic#1]
https://user-images.githubusercontent.com/8049534/123158782-e2206200-d474-11eb-90d1-f3078feaf7c7.mov

**Comment by alexmercerind** [comment]
Thanks for the report, unfortunately I haven't experienced the same.
Looking what's wrong.

**Comment by alexmercerind** [comment]
This is reproduced when the transparency effects in Personalization settings are disabled.
Enabling those will fix this.
