### ISSUE TITLE
macos transparency and effects only when focused

### ISSUE THREAD

**Issue by tofutim** [alexmercerind/flutter_acrylic#12]
Seems like the macos effects are only available when the window focused. Is there some way around this? The Mac Terminal Silver Aero does this kind of...

(I was hoping for a see-thru window)

**Comment by tofutim** [comment]
I guess maybe the blur is too much to give to a non-active app?

**Comment by alexmercerind** [comment]
> Seems like the macos effects are only available when the window focused. Is there some way around this? The Mac Terminal Silver Aero does this kind of...
> 
> (I was hoping for a see-thru window)

If you are aware of any relevant configurations or APIs, feel free to contribute. I haven't worked on macOS implementation, but I believe great work is done by @ Adrian-Samoticha.

**Comment by Adrian-Samoticha** [comment]
Most blurry apps in macOS work this way. Granted, the Terminal does seem to be an exception to this rule. I'll look into this sometime.

**Comment by Adrian-Samoticha** [comment]
#14 resolves this issue. You will be able to set the blur view state to `active` like so:
```dart
Window.setBlurViewState(MacOSBlurViewState.active);
```
This will make the window's blur effect active regardless of the window's active state.
