### ISSUE TITLE
Windows 11 bug: Setting WindowEffect.disabled after WindowEffect.mica will remove rounded corners and borders

### ISSUE THREAD

**Issue by alesimula** [alexmercerind/flutter_acrylic#15]
I'm making an app which has an option to choose whether to apply mica effect or not.

Setting WindowEffect.disabled right away causes no issues, but setting WindowEffect.mica and changing back to WindowEffect.disabled will remove rounded corners (Win 11) and window borders, which will come back when changing again to WindowEffect.mica

**Comment by alexmercerind** [comment]
I confirm this issue. I'll address this issue soon.

**Comment by alexmercerind** [comment]
I just wanted to inform this issue is reproducible only with `bitsdojo_window`. Working on the fix.

**Comment by alexmercerind** [comment]
![mug8J4efWu](https://user-images.githubusercontent.com/28951144/144696722-a467e09e-c8b8-4470-b911-a5db533cf9c8.gif)

Addressed in latest commit.
