### ISSUE TITLE
Example fails to build on Linux

### ISSUE THREAD

**Issue by Merrit** [alexmercerind/flutter_acrylic#17]
Example (and my own implementation) throws an exception.

Running on openSUSE Tumbleweed.

> Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method Initialize on channel com.alexmercerind/flutter_acrylic))

**Comment by alexmercerind** [comment]
As careless it may sound, I forgot to update the Linux method call handler since the plugin mainly targets Windows ("acrylic", "mica" are part of Windows 10/11). I released a "hot-fix" to address this issue.

Thanks.

**Comment by Merrit** [comment]
Can confirm, example now builds and transparency working well. Thank you! :heart: 🎉
