### ISSUE TITLE
App looks transparent on taskbar

### ISSUE THREAD

**Issue by aguilaair** [alexmercerind/flutter_acrylic#18]
The app is transparent on the taskbar, is there any way to not make it so?

![image](https://user-images.githubusercontent.com/29983481/149617205-e669524f-0fb9-46c0-9071-b825a897a5ce.png)

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Window.initialize();
  await Window.setEffect(
    effect: WindowEffect.mica,
    dark: false,
  );
  runApp(AppWrapper());
}
```

**Comment by alexmercerind** [comment]
I can't actually do anything about this, same is noticeable in Microsoft's own File explorer's header bar.
