### ISSUE TITLE
[BUG] Window shadows and window preview bugs

### ISSUE THREAD

**Issue by alesimula** [alexmercerind/flutter_acrylic#19]
I have found two bugs:

1. When mica is enabled and set to dark mode, the window shadow is twice as thick as it would be if it was disabled or set to light mode.
2. The window preview (hovering the mouse over the app icon) is transparent where the mica effect should be shown, this is especially noticeable in light mode:

![image](https://user-images.githubusercontent.com/3057584/149775421-a49ef2b3-00bb-4626-ac26-1ccdc2df36d3.png)
^ Actual window

![image](https://user-images.githubusercontent.com/3057584/149775498-8db44865-fc3c-4817-9d6a-25719de8b004.png)
^ Window preview

**Comment by aguilaair** [comment]
Same as #18, cannot be fixed. I just made sure my app has a dark mode to fit on the dark mode task bar.

**Comment by alesimula** [comment]
@alexmercerind I see, what about the first issue? (window shadow)

**Comment by aguilaair** [comment]
I am also able to replicate number 1 in my apps too @alexmercerind, both with a custom frame and the default one:

![image](https://user-images.githubusercontent.com/29983481/150634122-15d58bd3-a1dc-429b-ad53-16b6fc1ebf79.png)
![image](https://user-images.githubusercontent.com/29983481/150634173-4f16b1de-0795-43f0-a9b3-cd6a6d116d09.png)

**Comment by alexmercerind** [comment]
> I am also able to replicate number 1 in my apps too @alexmercerind, both with a custom frame and the default one:

@alesimula @aguilaair,

Same is noticeable in Windows's File Explorer. Intensity of the shadow seems to be higher in dark mode, but there is nothing I can do again. Best I can say is to inform Microsoft through Feedback Hub or support mail.
