### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by kirill-21** [alexmercerind/flutter_acrylic#20]
Will you add windows 7 support? Right now any app that uses this plugin can not be even launched on this windows version due to bitsdojo incompatibility but if you get rid of it and try to launch example app without it - any mode will show a black screen

**Comment by alexmercerind** [comment]
`DwmExtendFrameIntoClientArea` with negative `MARGINS` can be used for "sheet of glass" effect on Windows 7. Unfortunately I no longer own a machine that has Windows 7 compatibility to test this out.
