### ISSUE TITLE
[Linux] Add an option to remove window shadows

### ISSUE THREAD

**Issue by whiskeyPeak** [alexmercerind/flutter_acrylic#25]
Is there any way this is possible?
I'm trying to create custom bottom rounded corners and the shadows are getting in the way.

![Screenshot from 2022-04-08 12-37-06](https://user-images.githubusercontent.com/73116038/162421438-1d35c232-f0aa-426a-8fc3-76b4b02d0ca0.png)

**Comment by alexmercerind** [comment]
Closing. Removing the custom frame using bitsdojo_window for example, automatically gets rid of all window borders including shadows.
