### ISSUE TITLE
Window effects look strange on Windows 7 & 8.1 

### ISSUE THREAD

**Issue by tangenx** [alexmercerind/flutter_acrylic#26]
I rewrote the example with the [window_manager](https://pub.dev/packages/window_manager) library (because bitsdojo_window doesn't work on these systems) and ran it on virtual machines with Windows 7 and 8.1. And it looks... weird.

https://user-images.githubusercontent.com/46501450/166160284-5e5e42f6-f0b6-45a9-b89b-b89125074325.mp4

(I also ran an example from [fluent_ui](https://pub.dev/packages/fluent_ui) library.)

In Windows 8.1 (and in Windows 8, I guess) the effect is the same as in the video

**Comment by alexmercerind** [comment]
No effects work on any Windows version lower than Windows 10 1803.

**Comment by tangenx** [comment]
Thanks.

**Comment by alexmercerind** [comment]
> Thanks.

Dropping few of my other relevant work.
My fork of device_info_plus that you can use to query Windows version (that can be used to check for build higher or equal to 18362): https://github.com/fluttercommunity/plus_plugins/pull/814

My fork of bitsdojo_window with better resize hit-test & Windows 7 support (no hate on window_manager): https://github.com/bitsdojo/bitsdojo_window/pull/139

Anyways, I never used this project or "fluent design" in any of my Flutter projects. Not really that good looking when using without mica or other OSes, just becomes flat design.

**Comment by tangenx** [comment]
Thanks for the links you provided!
