### ISSUE TITLE
[Windows] Window text get a black/white background when using mica.

### ISSUE THREAD

**Issue by kolyneh** [alexmercerind/flutter_acrylic#27]
When showing the window text, it will get a black/white background when using mica.

Remove `BDW_CUSTOM_FRAME ` from `main.cpp` to show the origin window text.
```
// main.cpp  removed BDW_CUSTOM_FRAME
auto bdw = bitsdojo_window_configure( BDW_HIDE_ON_STARTUP );
```
![屏幕截图 2022-05-11 101028](https://user-images.githubusercontent.com/13062910/167754875-f8999dba-b853-4daf-8273-1535f9455a4a.png)

**Comment by alexmercerind** [comment]
Don't.

**Comment by kolyneh** [comment]
Hi Alex, could this be a Flutter issue, or maybe a Windows issue?

**Comment by alexmercerind** [comment]
Drawing custom frame is the only option. It's not possible to change the background of window title.
