### ISSUE TITLE
Can't run flutter_acrylic_example.exe 

### ISSUE THREAD

**Issue by zhiyiYo** [alexmercerind/flutter_acrylic#33]
I double-click exe but no window is displayed，do I need to install flutter on my computer to run `flutter_acrylic_example.exe`?

**Comment by alexmercerind** [comment]
> I double-click exe but no window is displayed，do I need to install flutter on my computer to run `flutter_acrylic_example.exe` ?

Do you see some error? Windows build & version?

**Comment by zhiyiYo** [comment]
@alexmercerind 
My Windows build version is 22621,  and I can't see any error message box when I double-click the exe😕

**Comment by zhiyiYo** [comment]
22000 can run exe😇

**Comment by alexmercerind** [comment]
The issue seems (was) to be in `bitsdojo_window` not here.
