### ISSUE TITLE
Weird performance issues while dragging app's window

### ISSUE THREAD

**Issue by ricard-v** [alexmercerind/flutter_acrylic#41]
Hi there.

First of all, thank you for tackling on the issue of translucent windows in desktop apps.

As stated in the title, I get really poor and weird performance when dragging my window:  it is very laggy and depending on the effect, it behaves erratically.

I have tested Windows only for now.

Using the following effects:
- Transparent: no issue, perfectly smooth
- Areo: quite laggy (definitely around 30 FPS, possily less)
- Acrylic: somewhat not that laggy, but slow as hell and erratic. When I drag the window, it lags behind my mouse. There is an after-effect where the mouse is stuck in the app. When I release my mouse, it re-appears and a few seconds later the app's window arrives at final position.
- Mica: cannot test (not using Windows 11).

Obviously I tried in profile & release mode but there is no effect. My computer is now slow:
- i don't get the same behavior with other Windows apps
- It sports a 7th Gen i7 Intel Core and a RTX 2070.

Does anyone get that issue ?

**Comment by HIHIQY1** [comment]
Same! With acrylic, moving the window just lags enormously, and the mouse cursor also lags behind, as you said.
As for aero, I don't have this issue; it works just fine.

On version `1.1.0+1`

**Comment by Adrian-Samoticha** [comment]
This is a bug in Windows 10. See related issue: #6
