### ISSUE TITLE
Mica does not react to window blurring when title bar is hidden

### ISSUE THREAD

**Issue by beta** [alexmercerind/flutter_acrylic#42]
Hi, I'm using flutter_acrylic together with [window_manager](https://pub.dev/packages/window_manager). My `main()` function writes as shown below.

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Window.initialize();

  await windowManager.ensureInitialized();
  const windowOptions = WindowOptions(
    title: _appName,
    size: Size(800, 600),
    center: true,
    // titleBarStyle: TitleBarStyle.hidden, // <- this line is the case
  );
  await windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });

  runApp(const GalleryApp());
}
```

And in my app widget's `initState()`:

```dart
  @override
  void initState() {
    super.initState();

    Window.setEffect(
      effect: WindowEffect.mica,
      dark: FluffApp.dark,
    );
  }
```

With `titleBarStyle: TitleBarStyle.normal` (the default value), mica works perfectly and turns solid properly when the window is blurred (losing focus).

- Focused
  ![image](https://user-images.githubusercontent.com/5000910/201869454-ebd36a5a-2fb1-4aa6-bd3b-48d3bb51331c.png)
- Blurred
  ![image](https://user-images.githubusercontent.com/5000910/201869486-882bdada-bcc6-41aa-87f2-e40fadc91bc5.png)

However after I set `titleBarStyle: TitleBarStyle.hidden`, the mica background does not react to focus changes any more.

- Focused
  ![image](https://user-images.githubusercontent.com/5000910/201869842-ef180113-4c7d-49a3-926c-5dd264ce27ed.png)
- Blurred. The focus is in the terminal app, but tbe mica background is still transparent.
  ![image](https://user-images.githubusercontent.com/5000910/201870184-0ec2f999-e030-412e-bf8f-ebc3bd9a81d7.png)

Please help to look into this problem, and let me know if I'm doing anything wrong. Thanks in advance.

**Comment by beta** [comment]
Environment: Flutter 3.3.8 (Channel stable) and Windows 11 22H2 (22621.819)

**Comment by alexmercerind** [comment]
I can't say anything unfortunately without getting into depth. I will still suspect `package:window_manager`. Window behaviour is closely tied with native Win32 calls.

**Comment by beta** [comment]
Tested with `bitsdojo_window` and the background is working correctly. I will close this issue and dig into the code of `window_manager` to see why.
