### ISSUE TITLE
Add MacOS support

### ISSUE THREAD

**Issue by aguilaair** [alexmercerind/flutter_acrylic#5]
An extension to #4, support MacOS

**Comment by alexmercerind** [comment]
Not assigning myself, I don't have a mac.

**Comment by hzlgnn** [comment]
is there any progress about the macOS support?

**Comment by alexmercerind** [comment]
@hzlgnn few people have found way to achieve the blur effect on macOS: [here](https://github.com/flutter/flutter/issues/59969). Although, its not part of any plugin yet. Assuming blur APIs on macOS are well documented, it might not be wrong to enable it globally.

**Comment by Adrian-Samoticha** [comment]
Alright, this is how far I've gotten thus far.

https://user-images.githubusercontent.com/86920182/139503010-342bbd92-78b9-42f5-a1ad-6dfdc7475988.mov

The extra functions that let you enter and exit out of fullscreen mode or hide and show the window controls are (currently) not supported, but the transparency effects work fine.

**Comment by Adrian-Samoticha** [comment]
@alexmercerind Alright. I've seen that you have approved my pull request. 🙂

The transparency effects are now fully supported, but the extra functions are not. I've decided to close this issue in favor of a newer one that addresses this issue: #10

**Comment by oryanmoshe** [comment]
> I have attempted to implement this on macOS and have so far achieved the following result:
> 
> ![image](https://user-images.githubusercontent.com/86920182/138447083-56adbca2-e801-4f4f-8fe9-0d4a15c5039b.png)
> 
> 
> The transparency effect works and is even sensitive to macOS' dark mode setting. This is what it looks like when dark mode is enabled:
> 
> ![image](https://user-images.githubusercontent.com/86920182/138447333-bfd8d549-910b-4747-b9d2-e6ab07c6195a.png)
> 
> That said, it seems that moving the window between workspaces causes the window's shadow to break:
> 
> ![image](https://user-images.githubusercontent.com/86920182/138447656-e12cb96e-0144-4a80-920d-fc66b226424c.png)
> 
> Resizing the window fixes the issue. I wonder if the issue could be resolved somehow by calling `MainFlutterWindow`'s `invalidateShadow()` method when a workspace change is detected, though I'm not sure.
> 
> Either way, the way I achieved this is by replacing the `MainFlutterWindow.swift` file in the Xcode workspace with Oryan Moshe's code I copied from the link you posted above:
> ````swift
> 
> import Cocoa
> import FlutterMacOS
> 
> class MainFlutterWindow: NSWindow {
>   override func awakeFromNib() {
>     let flutterViewController = FlutterViewController.init()
>     let windowFrame = self.frame
>     self.contentViewController = flutterViewController
>     self.setFrame(windowFrame, display: true)
>     RegisterGeneratedPlugins(registry: flutterViewController)
> 
>     /* Hiding the window titlebar */
>     self.titleVisibility = NSWindow.TitleVisibility.hidden;
>     self.titlebarAppearsTransparent = true;
>     self.isMovableByWindowBackground = true;
>     self.standardWindowButton(NSWindow.ButtonType.miniaturizeButton)?.isEnabled = false;
> 
>     /* Making the window transparent */
>     self.isOpaque = false
>     self.backgroundColor = .clear
> 
>     /* Adding a NSVisualEffectView to act as a translucent background */
>     let contentView = contentViewController!.view;
>     let superView = contentView.superview!;
> 
>     let blurView = NSVisualEffectView()
>     blurView.frame = superView.bounds
>     blurView.autoresizingMask = [.width, .height]
>     blurView.blendingMode = NSVisualEffectView.BlendingMode.behindWindow
> 
>     /* Pick the correct material for the task */
>     blurView.material = NSVisualEffectView.Material.underWindowBackground
> 
>     /* Replace the contentView and the background view */
>     superView.replaceSubview(contentView, with: blurView)
>     blurView.addSubview(contentView)
> 
>     super.awakeFromNib()
>   }
> }
> ````
> *Note*: You need to change the Deployment Target to 10.11 (or higher) for this to compile.
> 
> I've also edited the `MainMenu.xib` file, such that the `Full Size Content View` setting was enabled:
> 
> ![image](https://user-images.githubusercontent.com/86920182/138448708-d7bc2568-1f7b-43cb-b5fb-975cac09d66a.png)
> 
> This expands the area of the window that your Flutter app can draw to and would allow you to e.g. recreate the transparent sidebar that has become common these days while keeping the rest of the window opaque.
> 
> That said, I am not fluent in Swift and currently have a rather shallow understanding of how Flutter's platform channels work, but I'd assume if I did some reading on these subjects I could successfully implement that functionality into a Flutter package.

I'm glad to see I was helpful for your project! It's common practice to mention people using the @ sign in order for them to see that, but as long as someone found my research useful I'm happy (:
