### ISSUE TITLE
Release 1.1.0 on pub.dev

### ISSUE THREAD

**Issue by krjw-eyev** [alexmercerind/flutter_acrylic#52]
The latest release is nearly a year old. Would it be possible for the contributors to release a new version to pub.dev since there have been some changes which would really justify a new version?

**Comment by Adrian-Samoticha** [comment]
Sorry for taking this long, however, I'd like to say that I am planning to release 1.1.0 on pub.dev once #54 is resolved.

**Comment by Adrian-Samoticha** [comment]
Alright, version 1.1.0 has been released on pub.dev, however, #56 needs to be addressed soon. Either way, the package is released and does, of course, support macOS. Don't get fooled by its lack of a macOS platform support badge.
