### ISSUE TITLE
macOS broken

### ISSUE THREAD

**Issue by jinfagang** [alexmercerind/flutter_acrylic#64]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/21303438/221761080-5a21b309-d478-4649-873b-97b0166d4d71.png">

aera effect not work any more...

Please maintain this good repo, please post workable code before release, many users depends on this!!

**Comment by jinfagang** [comment]
@damywise AM using flutter 3.7.5

**Comment by Adrian-Samoticha** [comment]
Done. Simply upgrading to flutter_acrylic 1.1.1 should fix the problem.

**Comment by Adrian-Samoticha** [comment]
Apparently static analysis failed on pub.dev. I have run `flutter analyze lib/window.dart` using lints_core and couldn't reproduce the issue. I'll see what I can do later.

**Comment by jinfagang** [comment]
Oh,

**Comment by jinfagang** [comment]
@Adrian-Samoticha  windows failed build

![图片](https://user-images.githubusercontent.com/21303438/222050618-01481390-b58c-4d61-a41a-3952c1dd00e9.png)

**Comment by jinfagang** [comment]
remove macos_windows_utils depdency on windows? it's not properly to using macos api on windows.

**Comment by Adrian-Samoticha** [comment]
The issue isn't Windows-related. I was able to reproduce it on macOS as well. I am currently still investigating it.
