### ISSUE TITLE
hideTitle takes no effect

### ISSUE THREAD

**Issue by jinfagang** [alexmercerind/flutter_acrylic#74]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/21303438/228877018-f6c0d77b-a804-40ee-8035-27998adfcdbb.png">

**Comment by Adrian-Samoticha** [comment]
`hideTitle` is a macOS-only method. If you’d like to hide the entire title bar, you might be interested in [window_plus](https://github.com/alexmercerind/window_plus).

**Comment by jinfagang** [comment]
@Adrian-Samoticha hello, I am confused, I just follow the demo code, it looks demo code can hide the bar.

I have another app which using actually same setups, it can hide the title, but this one can not,,, very confused.
