### ISSUE TITLE
Not work after importing flutter_easyloading

### ISSUE THREAD

**Issue by olers** [alexmercerind/flutter_acrylic#77]
I have imported [flutter_easyloading](https://pub.flutter-io.cn/packages/flutter_easyloading) in the current MacOS desktop application. The initialization operations of this package are:

```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: EasyLoading.init(),
    );
  }
}
```

After `builder: EasyLoading.init(),`，the `flutter_acrylic` doesn't work.

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/21333287/234742627-bfa6b536-f381-4cf8-8250-a1562e9fedb9.png">

**Comment by Adrian-Samoticha** [comment]
It appears that flutter_easyloading is drawing a background that covers the transparency effect. To get your transparent background back, you can wrap your `MyAppBody` widget in a `DecoreatedBox` with `backgroundBlendMode: BlendMode.clear` like this:

```dart
⋮
home: DecoratedBox(
  decoration: BoxDecoration(
    color: Colors.transparent,
    backgroundBlendMode: BlendMode.clear,
  ),
  child: MyAppBody(),
),
builder: EasyLoading.init(),
⋮
```

It seems that both flutter_acrylic and flutter_easyloading work correctly this way:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/86920182/234793414-1fc20bd5-149a-47c8-a43d-c3fd3b4f457b.png">
