### ISSUE TITLE
Tint colour does not work on Mac OS when using WindowEffect.acrylic 

### ISSUE THREAD

**Issue by nialljawad96** [alexmercerind/flutter_acrylic#83]
There is no red tint, and tint does not change when adjusting the color parameter. 

```
setEffect() async {

    await Window.setEffect(
      effect: WindowEffect.acrylic,
      color: Colors.red,

    );

}

```

**Comment by Adrian-Samoticha** [comment]
The `color` argument only has an effect when using the `acrylic`, `aero`, `solid`, or `transparent` effects, none of which are supported on macOS (flutter_acrylic just falls back on one of the supported effects, instead).

If you wish to apply a color to your window, you’ll need to do that using a Flutter widget.

**Comment by nialljawad96** [comment]
@Adrian-Samoticha Cool, I'd probably say to just add that into the documentation as the table on the main page says Mac OS is supported for acrylic - could maybe add which supported effect it falls back onto, too. 

Thanks for making this awesome package!
